# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/
Accept: application/json

###
GET http://127.0.0.1:8000/anime-titles/
Accept: application/json

###
GET http://127.0.0.1:8000/game/get-location?lat=40.7128&lng=-74.0060&guess_number=2
Accept: application/json

###
GET http://127.0.0.1:8000/game/get-location-from-db
ACCEPT: application/json